name: Kafka smoke test (runner)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl wget tar netcat-openbsd

      - name: Run setup script (no start)
        shell: bash
        run: |
          bash .devcontainer/scripts/setup-kafka.sh

      - name: Start Kafka (daemon)
        shell: bash
        run: |
          bash .devcontainer/scripts/start-kafka-daemon.sh

      - name: Wait for Kafka port
        shell: bash
        run: |
          for i in $(seq 1 60); do
            if nc -z localhost 9092; then echo "Kafka is up"; exit 0; fi
            sleep 1
          done
          echo "Kafka did not start in time" >&2; exit 1

      - name: Smoke test - create/list topic
        shell: bash
        run: |
          kafka-topics.sh --bootstrap-server localhost:9092 --create --topic ci-smoke --partitions 1 --replication-factor 1 || true
          kafka-topics.sh --bootstrap-server localhost:9092 --list | grep -q ci-smoke

      - name: Smoke test - produce/consume
        shell: bash
        run: |
          set -e
          echo "hello" | kafka-console-producer.sh --bootstrap-server localhost:9092 --topic ci-smoke >/dev/null
          kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic ci-smoke --from-beginning --timeout-ms 5000 | grep -q hello

      - name: Stop Kafka
        if: always()
        shell: bash
        run: |
          bash .devcontainer/scripts/stop-kafka.sh || true

